# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12240f3edfc4c64f9031ae52f21c0dd3d0063836f5442194cb83e8bcbf8b7f0bc09027ed12a5cc8abdc25dc06969fc214eb92ff8b87515077d785debd608d932

test:
  secret_key_base: 72ec3b81240bbea7e87fa81e335ae638d72998cb19c85006cd9041aa34e54eb380d553742397baee264f102504747dd8f4c499dece83521b54492fc295fa6786

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
